### PR TITLE
Fixing to support Python 3

### PR DESCRIPTION
**Pull request by vivekpatani**
I do not know if the fixes for OSX would work or not, but fixes for Linux should be just fine. Referencing #46 and #40

### CODE REVIEW

**Comment by jennytianne** [comment]
I have OSX and I'm still running into the same syntax error problems as in  #40 for python 3. Should I change it to python 2?

**Comment by staticdev** [comment]
@karpathy any chance this get merged to original repo? Python2 end-of-life was 3 Jul 2010. If you don't want to maintain this project I have interest also to cleanup this PRs.

**Comment by plsnotracking** [comment]
I do not think, this project is live, I would fork and it merge any PRs or just find another library to work with. @staticdev

**Comment by vivekpatani** [comment]
project seems to be dead, will close PR.

**Pull request closed without merging**
